#!/usr/bin/perl

=about

Author: Farhad Mehdizada (@ferhadme)

Perl script for visualizing repository summaries recursively starting from the specified directory location
Uses git-summary (git-extras) as a dependency

Usage: ./git-summmary starting-directory

base directory                  : <base directory name>
repo age (oldest / latest)      : <oldest> / <latest>
active (earliest / most recent) : <earliest> / <most recent>
commits                         : <total number of commits>
files                           : <total number of files>
TODO: authors...

=cut

use strict;
use warnings;
use v5.32;

sub main {
    my $path = shift @ARGV or die &usage;
    if (not defined $path) {
	die &usage;
    }

    my $git_summary_path = system("which git-summary");
    if ($git_summary_path != 0) {
	die "git-summary (git-extras) as a dependency not found";
    }

    my %summary_hash;
    &traverse_repos($path, %summary_hash);
    &show_git_summmary(%summary_hash);
}

sub traverse_repos {
    (my $path, my %summary_hash) = (@_);

    if (not -d $path) {
	return;
    }

    chdir($path);
    if (-d ".git") {
	print "Git repository found ", $path, "\n";
	&calculate_summary(%summary_hash);
    }

    foreach my $dir (<*>) {
	&traverse_repos($dir, %summary_hash);
    }

    chdir("..");
}

sub calculate_summary {
    my %summary_hash = (@_);
    my $current_summary = `git summary`;

    # ($summary_hash{'title'}, $summary_hash{'value'}) = ("Title", 2);

    print $current_summary, "\n";
}

sub show_git_summmary {
    print("base directory", (" " x 18), ": ", "VALUE", "\n");
    print("repo age (oldest / latest)", (" " x 6), ": ", "VALUE", "\n");
    print("active (earliest / most recent)", (" " x 1), ": ", "VALUE", "\n");
    print("commits", (" " x 25), ": ", "VALUE", "\n");
    print("files", (" " x 27), ": ", "VALUE", "\n");

    # TODO: authors...
}

sub usage {
    "Usage: ";
}

# sub options {
#     (
#      {
# 	 "title" => "base directory",
# 	     "space" => 18,
# 	     ""
#      },
#      {
#      }
#     );
# }

main;
exit;
